'webform.webform.*.third_party.webform_prepopulate':
  type: mapping
  label: Webform Prepopulate
  mapping:
    form_prepopulate_enable_file:
      type: boolean
      label: 'Use a file to prepopulate'
    csv_delimiter:
      type: string
      label: 'CSV file delimiter'
    disable_hash_access_limit:
      type: boolean
      label: 'Disable access limit to several hashes for prepopulating a Webform.'
    delete_data_on_webform_close:
      type: boolean
      label: 'Delete data when the Webform is closed'
