<?php

/**
 * @file
 * Contains webform_nouislider.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_nouislider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform noUISlider module.
    case 'help.page.webform_nouislider':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add a noUiSlider to webform as element.') . '</p>';
      return $output;

    default:
  }
}
