<?php

/**
 * @file
 * Primary module hooks for Webform Summation Field module.
 */

use Drupal\webform\Entity\WebformSubmission;

/**
 * Implements hook_theme().
 */
function webform_summation_field_theme() {

  $info = [
    'webform_summation_field' => [
      'render element' => 'element',
    ],
  ];

  return $info;
}

/**
 * Implements hook_webform_submission_presave().
 */
function webform_summation_field_webform_submission_presave(WebformSubmission $webform_submission) {
  $webform_summation_field_key = '';
  $webform_summation_field_collect_fields = [];
  $webform = $webform_submission->getWebform();
  $webform_fields = $webform->getElementsDecoded();

  foreach ($webform_fields as $key => $value) {
    if (isset($value['#type']) && $value['#type'] == 'webform_summation_field') {
      $webform_summation_field_key = $key;
      $webform_summation_field_collect_fields = $value['#collect_field'];
      break;
    }
  }

  if ($webform_summation_field_key) {
    $data = $webform_submission->getData();
    $result = 0;
    foreach ($data as $key => $value) {
      if (in_array($key, $webform_summation_field_collect_fields)) {
        $result += $value;
      }
    }
    $data[$webform_summation_field_key] = $result;
    $webform_submission->setData($data);
    $webform_submission->setElementData($webform_summation_field_key, $result);
    $webform->invokeHandlers('overrideSettings', $webform_submission);
  }
}
